version: 2

updates:
  - package-ecosystem: docker-compose
    directories:
      - /docker/alertmanager
      - /docker/authentik
      - /docker/blackbox-exporter
      - /docker/caddy
      - /docker/collabora
      - /docker/elasticsearch
      - /docker/grafana
      - /docker/libredesk
      - /docker/libredesk-redis
      - /docker/nextcloud
      - /docker/node-exporter
      - /docker/postgres
      - /docker/prometheus
      - /docker/redis
      - /docker/talk-hpb
      - /docker/vaultwarden
      - /hosts/nctest/docker/uptime-kuma
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 12
