services:
  nextcloud-talk-hpb:
    image: ghcr.io/nextcloud-releases/aio-talk:latest
    container_name: nextcloud-talk-hpb

    restart: unless-stopped

    env_file:
      - .env

    environment:
      NC_DOMAIN: ${NC_DOMAIN}
      TALK_PORT: ${TALK_PORT}
      TURN_SECRET: ${TURN_SECRET}
      SIGNALING_SECRET: ${SIGNALING_SECRET}
      INTERNAL_SECRET: ${INTERNAL_SECRET}

    ports:
      - "${HPB_PORT}:8081"

    networks:
      - nextcloud

networks:
  nextcloud:
    external: true
    name: nextcloud_default
