services:
  server:
    container_name: authentik-server

    image: ghcr.io/goauthentik/server:2026.5.4

    command: server

    restart: unless-stopped

    env_file:
      - .env

    environment:
      AUTHENTIK_POSTGRESQL__HOST: ${PG_HOST}
      AUTHENTIK_POSTGRESQL__PORT: ${PG_PORT}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_OUTPOSTS__DISCOVER: "false"

    shm_size: 512mb

    volumes:
      - /srv/zircula/authentik/data:/data
      - /srv/zircula/authentik/templates:/templates

    networks:
      - frontend
      - backend

  worker:
    container_name: authentik-worker

    image: ghcr.io/goauthentik/server:2026.5.4

    command: worker

    restart: unless-stopped

    env_file:
      - .env

    environment:
      AUTHENTIK_POSTGRESQL__HOST: ${PG_HOST}
      AUTHENTIK_POSTGRESQL__PORT: ${PG_PORT}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_OUTPOSTS__DISCOVER: "false"

    shm_size: 512mb

    volumes:
      - /srv/zircula/authentik/data:/data
      - /srv/zircula/authentik/certs:/certs
      - /srv/zircula/authentik/templates:/templates

    networks:
      - backend

networks:
  frontend:
    external: true
    name: zircula_frontend

  backend:
    external: true
    name: zircula_backend
