services:
  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}

    container_name: nextcloud

    restart: unless-stopped

    env_file:
      - .env

    environment:
      TZ: ${TZ}

      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: redis

      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT}

    volumes:
      - /srv/zircula/nextcloud/html:/var/www/html
      - /srv/zircula/nextcloud/data:/var/www/html/data

    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
    name: zircula_frontend

  backend:
    external: true
    name: zircula_backend
